#!/bin/sh

# 一:kill xargs
# ps -ef | grep procedure_name | grep -v grep | awk '{print $2}' | xargs kill -9

# 二:$#为传递到脚本的参数个数 -lt为检测左边的数是否小于右边的，如果是，则返回 true
if [ $# -lt 1 ]
then
  echo "缺少参数：procedure_name"
  exit 1
fi

PROCESS=`ps -ef|grep $1|grep -v grep|grep -v PPID|awk '{ print $2}'`
for i in $PROCESS
do
  echo "Kill the $1 process [ $i ]"
  kill -9 $i
done

# 三:example_demo
PROCESS=`ps -ef | grep uwsgi | grep -v grep | grep root | awk '{print $2}'`
for i in $PROCESS
do
    echo "kill the uwsgi process  ${i} "
    sudo kill -9 ${i}
    sudo uwsgi -i /data/CTF2.0_2.1/uwsgi.ini
done

PROCESS=`ps -auxf | grep celery | grep -v grep  | awk '{print $2}'`
for i in $PROCESS
do
    echo "kill the celery process  ${i} "
    sudo kill -9 ${i}
done
